### ISSUE TITLE
Can't define where to place custom nodes

### ISSUE THREAD

**Issue by spartacus-zeus** [congressus/sepa-direct-debit#16]
For ABN AMRO you need to specify ```<Othr><Id><NOT PROVIDED>``` if you don't provide a BIC. 

DbtrAgt, however, is not allowed at the bottom. So I changed the addCustomNode a bit:

```php
public function addCustomNode($parent_XPATH, $name, $value = "", $attr = array() , $beforethiselement = ""){

//AND

if ( !empty($beforethiselement) ) {
	$beforethiselement = $xpath->query($beforethiselement);
	$parent->item(0)->insertBefore($newnode,$beforethiselement->item(0));
}
else {        
	$parent->item(0)->appendChild($newnode); // original append
}
```

**Comment by JelleM-Congressus** [comment]
Please see the updated documentation (you should call save() before and after and also check out the usage of last() in the XPATH). Thanks for noticing!
