### ISSUE TITLE
batch = false gives configuration exception

### ISSUE THREAD

**Issue by jpicaude** [congressus/sepa-direct-debit#21]
If I set batch  to false, the following Exception is fired : 

     Uncaught exception 'Exception' with message 'Invalid config file: batch is empty.'

After searching, it seems that the configuration validation checks for "batch" value with the empty() function, but false makes empty() return true, and then raises the exception.

**Comment by JelleM-Congressus** [comment]
Will look into this, generally banks only accept batch = True, however your point is valid indeed.

**Comment by JelleM-Congressus** [comment]
Fixed, thanks for the feedback!
