### ISSUE TITLE
Validate IBAN capital letters

### ISSUE THREAD

**Issue by si4dev** [congressus/sepa-direct-debit#22]
I do appreciate your nice and simple solution with real XML creation (not string output). I noticed one improvement you could make.

Instead of 
```php
       //If using lower than PHP 5.4.0, there is no ENT_XML1
        if( version_compare(PHP_VERSION, '5.4.0') >= 0){
            $NmNode->nodeValue = htmlentities($this->config['name'],ENT_XML1, 'UTF-8' );
        }else{
            $NmNode->nodeValue = htmlentities($this->config['name'],ENT_QUOTES, 'UTF-8' );
        }
```

You can use 
```php
        $NmNode->appendChild( $this->xml->createTextNode( $this->config['name'] ) );
```
        
As **createTextNode** is very powerful and will escape the xml reserved characters and is designed to do this.

I also like your validation rules. I noticed that the bank needs the IBAN to be in capital letters. Maybe you can add this check as well?

**Comment by JelleM-Congressus** [comment]
I am unsure whether all banks require capitals but I will add the check anyway. With regards to your createTextNode I will have to do additional testing since this can potentially break everyones implementation.

**Comment by si4dev** [comment]
You might be right that some part of the IBAN does support lowercase. I see Format: [A-Z]{2,2}[0-9]{2,2}
[a-zA-Z0-9]{1,30}

In this document http://businessbanking.bankofireland.com/fs/doc/wysiwyg/sepa-direct-debit-pain-008-001-02-xml-file-structure-july-2013.pdf

So better keep it like you have or maybe check against this regular expression

**Comment by JelleM-Congressus** [comment]
Fixed the IBAN Validation, will perhaps look into createTextNode later. Do you mind if I close your issue?

**Comment by si4dev** [comment]
For me you can close the issue although I cannot yet confirm proper working for your fixes. Thanks anyway.
