### ISSUE TITLE
XML line too long

### ISSUE THREAD

**Issue by si4dev** [congressus/sepa-direct-debit#23]
I do get the complete XML document as one or two lines. This brings two issues during the import to my bank. [1] with many requests (I see it already with 10) the document is not accepted. [2] my bank reports errors with line numbers and it will not be possible to identify the root cause of errors.

The solution is simple to nicely format the XML with the build-in settings:

Just after this line
```php
  $this->xml = new DOMDocument("1.0","UTF-8");
```
Add these two:
```php
        $this->xml->preserveWhiteSpace = false;
        $this->xml->formatOutput = true;
```

Now every xml tag will show on a new line and errors with references to line numbers are now more easy to debug.

**Comment by JelleM-Congressus** [comment]
Banks SHOULD accept it as one line, but I will test you fix on this one and integrate it if it will not cause problems. (It currently validates against the schema, however banks are usually not really schema compliant even though SEPA was designed to mitigate different standards.....)

**Comment by si4dev** [comment]
I do agree that banks should accept one line XML as it remains valid XML. Still for own readability I would also like to see the xml with multiple lines. And for my bank system which returns errors with line numbers it is really helping.

About createTextNode it would indeed need testing. I did get an error on a name using &. So I reviewed the code and I remembered that I used createTextNode in another project. When I changed it to createTextNode then the file was validated correctly on the & sign. Anyway that will indeed not proof that it will work in all situations although I do have great trust.

I leave it up to you and thanks and again thanks for the effort as the import is nicely working now

**Comment by JelleM-Congressus** [comment]
The name requires latin-1 as charset anyway afaik (SEPA requirement). there is an XML validator (against an xsd) in this project which I highly recommend. Errors with the bank tend to be custom rules or, more often, wrong IBANs (you can validate the checksum on position 2-3 yourself).

-------- Origineel bericht --------
Van:si4dev <notifications@github.com>
Verzonden:Sat, 09 Jan 2016 14:47:57 +0100
Aan:congressus/sepa-direct-debit <sepa-direct-debit@noreply.github.com>
Cc:Jelle van der Molen <jelle@congressus.nl>
Onderwerp:Re: [sepa-direct-debit] XML line too long (#23)

**Comment by JelleM-Congressus** [comment]
Fixed the IBAN Validation, will perhaps look into createTextNode later. Do you mind if I close your issue?
