### ISSUE TITLE
Generate Transfers?

### ISSUE THREAD

**Issue by pedrocortizo** [congressus/sepa-direct-debit#24]
It is planned to complete this development with the possibility of issuing transfers from one account to multiple recipients?

It is a development that we need to pay for scholarships for students and would be very useful

If this feature is not provided, we would appreciate if you can tell me any existing library that automates this task.

Thank you

**Comment by JelleM-Congressus** [comment]
You are talking about SEPA Credit Transfers also known as SCT. Google gives this as an good option: https://github.com/blaaat/php-sepa-credit-transfer
