### ISSUE TITLE
IBAN Validation

### ISSUE THREAD

**Issue by i6media** [congressus/sepa-direct-debit#27]
Hi,

We're experiencing some issues with the IBAN Validation and French IBAN Numbers. It says it doesn't validate, however the IBAN is Correct. If we use a different library for the validation it validates (I can give you a valid French in a PM if you like).

In my humble opinion the IBAN Validation method in the SEPA Class is really limited and needs to be extended (with for example: https://github.com/globalcitizen/php-iban).

**Comment by JelleM-Congressus** [comment]
I agree with you however using the globalcitizen version is kinda tricky given the licensing (LGPL) and ours (MIT). I propose to make the IBAN validation optional (with a config flag) and advise users to use a proper library such as the globalcitizen library. The validation of IBAN's is also a bit out of scope for this project and added as an extra.

**Comment by i6media** [comment]
I agree, if it's optional it will resolve the issue. If one can decide for himself if he uses his own library or not it will be much better. Now because it's mandatory it generates an exception and we can't use this library with certain (valid) IBAN numbers. 

Cheers!

**Comment by JelleM-Congressus** [comment]
Made a fix for this :) Is this acceptable?

**Comment by i6media** [comment]
Looks great! Thanks in advance
