### ISSUE TITLE
[Question] return the PmtInfId 

### ISSUE THREAD

**Issue by bady1985** [congressus/sepa-direct-debit#28]
Sorry, I haven't found a place for Qustions.

I see that the script has the ability to return the end_to_end_id when you use this
```
try{
    $endToEndId = $SEPASDD->addPayment($payment);
}catch(Exception $e){
    echo $e->getMessage();
}
```

, is it possible do make this with the PmtInfId, too?

**Comment by JelleM-Congressus** [comment]
sure, change line 373:
`return $EndToEndIdNode->nodeValue;`
to:
`return $PmtInfIdNode->nodeValue;`
or if you want both:
`return array($EndToEndIdNode->nodeValue, $PmtInfIdNode->nodeValue);`

Does that answer your question or was it more of a feature request?

**Comment by JelleM-Congressus** [comment]
Still haven't heard from you, so I will close the question soon if that's ok with you or if I don't hear back.
